version: "3.9"
services: 
  postgres:
    image: postgres:16
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"

  api:
    image: hugocbb/app-super-gestao:1.2
    ports:
    - "8080:8080"

  frontend:
    image: hugocbb/app-super-gestao-frontend:1.0
    ports:
    - "5173:5173"
